# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Patankar scheme for modelling oxygen depletion
#'
#' This function returns a data frame containing results from the oxygen model.
#'
#' @param times An integer vector
#' @param y start concentration of O2
#' @param Flux A numeric vector of O2 fluxes. One value per iteration
#' @param Khalf A numeric vector for Khalf. One value per iteration
#' @param Theta A numeric vector for Theta. One value per iteration
#' @param Area_linear
#' @param Temp_linear
#' @param Volume_linear
#' @param iterations
#' @export
o2_model_patankarrk2_cpp <- function(times, y, onset, Flux, Khalf, Theta, Area_linear, Temp_linear, Volume_linear, iterations) {
    .Call(`_oxypatankr_o2_model_patankarrk2_cpp`, times, y, onset, Flux, Khalf, Theta, Area_linear, Temp_linear, Volume_linear, iterations)
}

#' Patankar scheme for modelling oxygen depletion
#'
#' This function returns a data frame containing results from the oxygen model.
#'
#' @param times An integer vector
#' @param y start concentration of O2
#' @param Flux A numeric vector of O2 fluxes. One value per iteration
#' @param Khalf A numeric vector for Khalf. One value per iteration
#' @param Theta A numeric vector for Theta. One value per iteration
#' @param Area_linear
#' @param Temp_linear
#' @param Volume_linear
#' @param iterations
#' @export
o2_model_lsoda_cpp <- function(y, times, forcings, events, Flux, Khalf, Theta, iterations) {
    .Call(`_oxypatankr_o2_model_lsoda_cpp`, y, times, forcings, events, Flux, Khalf, Theta, iterations)
}

